- hosts: all
  gather_facts: false
  tasks:
  - name: Actualizar el sistema
    ansible.builtin.shell: 'yum update -y

      '
    become: true
  - name: Instalar httpd
    ansible.builtin.shell: 'yum install httpd -y

      '
    become: true
  - name: Iniciar y habilitar el servicio httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
