---
- name: Generar archivo de texto con versión de Linux
  hosts: all
  gather_facts: yes
  tasks:
    - name: Determinar la distribución de Linux
      set_fact:
        linux_distribution: "{{ ansible_distribution | lower }}"

    - name: Mostrar información de depuración
      debug:
        msg: 
          - "Distribución: {{ ansible_distribution }}"
          - "Versión: {{ ansible_distribution_version }}"
          - "Usuario SSH: {{ ansible_ssh_user }}"

    - name: Crear archivo en el directorio home correspondiente
      copy:
        content: "archivo generado por ansible\nVersión de Linux: {{ ansible_distribution }} {{ ansible_distribution_version }}"
        dest: "/home/{{ ansible_ssh_user }}/archivo_generado.txt"
      when: linux_distribution in ['centos', 'redhat', 'ubuntu']
      become: true  # Necesario para permisos de escritura

    - name: Mostrar ruta donde se debería guardar el archivo
      debug:
        msg: "El archivo se intentará guardar en: /home/{{ ansible_ssh_user }}/archivo_generado.txt"

    - name: Mensaje de error si la distribución no es válida
      debug:
        msg: "Distribución no válida: {{ linux_distribution }}. No se creó el archivo."
      when: linux_distribution not in ['centos', 'redhat', 'ubuntu']
...
