---
- name: Generar archivo de texto con versión de Linux
  hosts: all
  gather_facts: yes  # Recolectamos información del sistema
  tasks:
    - name: Determinar la distribución de Linux
      set_fact:
        linux_distribution: "{{ ansible_distribution | lower }}"

    - name: Crear archivo en el directorio home correspondiente
      copy:
        content: "archivo generado por ansible\nVersión de Linux: {{ ansible_distribution }} {{ ansible_distribution_version }}"
        dest: "/home/{{ linux_distribution }}/archivo_generado.txt"
      when: linux_distribution in ['centos', 'rhel', 'ubuntu']
      become: true  # Si es necesario para permisos de escritura en el directorio home

    - name: Mensaje de error si la distribución no es válida
      debug:
        msg: "Distribución no válida: {{ linux_distribution }}. No se creó el archivo."
      when: linux_distribution not in ['centos', 'rhel', 'ubuntu']
...
