---
- name: Instalar Grafana y MySQL en servidores desde CSV
  hosts: localhost
  become: yes
  vars:
    grafana_password: password
    mysql_root_password: rootpassword
    csv_file: "{{ playbook_dir }}/inventory/grafana.csv"  # Ruta del archivo CSV
    delimiter: ";"

  tasks:
    - name: Verificar que el archivo CSV existe
      stat:
        path: "{{ csv_file }}"
      register: file_check

    - name: Fallar si el archivo de inventario no existe
      fail:
        msg: "El archivo de inventario {{ csv_file }} no existe."
      when: not file_check.stat.exists

    - name: Leer contenido del archivo CSV
      set_fact:
        csv_content: "{{ lookup('file', csv_file) }}"

    - name: Extraer encabezados del CSV
      set_fact:
        headers: "{{ csv_content.split('\n') | first | split(delimiter) | map('trim') | list }}"

    - name: Extraer filas del CSV
      set_fact:
        rows: "{{ csv_content.split('\n')[1:] | reject('match', '^$') | list | map('split', delimiter) | list }}"

    - name: Validar que cada fila tenga el mismo número de campos que los encabezados
      fail:
        msg: "La fila {{ row }} no tiene el mismo número de campos que los encabezados."
      when: row | length != headers | length
      loop: "{{ rows }}"
      loop_control:
        loop_var: row

    - name: Combinar encabezados con filas para crear diccionarios
      set_fact:
        csv_data: "{{ csv_data | default([]) + [ dict(headers | zip(row)) ] }}"
      loop: "{{ rows }}"
      loop_control:
        loop_var: row

    - name: Agregar hosts dinámicamente al grupo 'dynamic_hosts'
      add_host:
        name: "{{ item.IP }}"
        groups: dynamic_hosts
        ansible_host: "{{ item.IP }}"
        ansible_user: "{{ item.Usuario }}"
        ansible_password: "{{ item.Contraseña }}"
        ansible_connection: ssh
        ansible_ssh_pass: "{{ item.Contraseña }}"
      loop: "{{ csv_data }}"
      loop_control:
        loop_var: item

    - name: Instalar dependencias para MySQL
      package:
        name:
          - mysql-server
          - mysql-client
          - libmysqlclient-dev
        state: present
      become: yes
      when: ansible_host is defined

    - name: Iniciar y habilitar MySQL
      service:
        name: mysqld
        state: started
        enabled: yes
      become: yes
      when: ansible_host is defined

    - name: Configurar la contraseña del usuario root de MySQL
      shell: |
        mysqladmin -u root password "{{ mysql_root_password }}"
      ignore_errors: yes
      become: yes
      when: ansible_host is defined

    - name: Instalar Grafana en el servidor
      package:
        name: grafana
        state: present
      become: yes
      when: ansible_host is defined

    - name: Iniciar y habilitar el servicio de Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes
      become: yes
      when: ansible_host is defined

    - name: Configurar la contraseña de admin en Grafana
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: '^#admin_password ='
        line: 'admin_password = admin'
      notify:
        - Reiniciar Grafana
      become: yes
      when: ansible_host is defined

    - name: Crear base de datos para Grafana
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "CREATE DATABASE IF NOT EXISTS grafana;"
      ignore_errors: yes
      become: yes
      when: ansible_host is defined

    - name: Crear usuario de base de datos para Grafana
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "GRANT ALL PRIVILEGES ON grafana.* TO 'grafana'@'localhost' IDENTIFIED BY '{{ grafana_password }}';"
      ignore_errors: yes
      become: yes
      when: ansible_host is defined

    - name: Crear tabla de inventario de servidores
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "USE grafana; CREATE TABLE IF NOT EXISTS servidores (
          id INT AUTO_INCREMENT PRIMARY KEY,
          ip VARCHAR(15) NOT NULL,
          distribucion_linux VARCHAR(50) NOT NULL,
          version_linux VARCHAR(20) NOT NULL,
          soportada VARCHAR(50) NOT NULL,
          vulnerabilidad_alta INT DEFAULT 0,
          vulnerabilidad_media INT DEFAULT 0,
          vulnerabilidad_baja INT DEFAULT 0,
          cantidad_procesadores INT DEFAULT 1,
          cantidad_ram INT DEFAULT 0,
          cantidad_disco INT DEFAULT 0
        );"
      ignore_errors: yes
      become: yes
      when: ansible_host is defined

  handlers:
    - name: Reiniciar Grafana
      service:
        name: grafana-server
        state: restarted
      become: yes
