---
- name: Instalar Grafana, MySQL y configurar inventario de servidores
  hosts: localhost
  become: yes
  vars:
    # Configuraci칩n de conexi칩n al servidor
    ansible_host: 192.168.100.58
    ansible_user: grafana
    ansible_ssh_pass: password
    ansible_python_interpreter: /usr/bin/python3  # Especificar Python 3
    grafana_user: grafana
    grafana_password: password
    mysql_root_password: rootpassword

  tasks:
    - name: Instalar dependencias para MySQL
      package:
        name: 
          - mysql-server
          - mysql-client
          - libmysqlclient-dev
        state: present

    - name: Iniciar y habilitar MySQL
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Configurar la contrase침a del usuario root de MySQL
      shell: |
        mysqladmin -u root password "{{ mysql_root_password }}"
      ignore_errors: yes

    - name: Instalar Grafana en el servidor
      package:
        name: grafana
        state: present

    - name: Iniciar y habilitar el servicio de Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Configurar la contrase침a de admin en Grafana
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: '^#admin_password ='
        line: 'admin_password = admin'
      notify:
        - Reiniciar Grafana

    - name: Crear base de datos para Grafana
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "CREATE DATABASE IF NOT EXISTS grafana;"
      ignore_errors: yes

    - name: Crear usuario de base de datos para Grafana
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "GRANT ALL PRIVILEGES ON grafana.* TO 'grafana'@'localhost' IDENTIFIED BY '{{ grafana_password }}';"
      ignore_errors: yes

    - name: Crear tabla de inventario de servidores
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "USE grafana; CREATE TABLE IF NOT EXISTS servidores (
          id INT AUTO_INCREMENT PRIMARY KEY,
          ip VARCHAR(15) NOT NULL,
          distribucion_linux VARCHAR(50) NOT NULL,
          version_linux VARCHAR(20) NOT NULL,
          soportada VARCHAR(50) NOT NULL,
          vulnerabilidad_alta INT DEFAULT 0,
          vulnerabilidad_media INT DEFAULT 0,
          vulnerabilidad_baja INT DEFAULT 0,
          cantidad_procesadores INT DEFAULT 1,
          cantidad_ram INT DEFAULT 0,
          cantidad_disco INT DEFAULT 0
        );"
      ignore_errors: yes

  handlers:
    - name: Reiniciar Grafana
      service:
        name: grafana-server
        state: restarted
