---
- name: Mostrar el contenido de la llave privada y obtener información del servidor remoto
  hosts: local  # La máquina en la que se ejecuta el playbook
  gather_facts: no  # No es necesario recopilar hechos para esta tarea

  tasks:
    - name: Leer el contenido de la llave privada
      slurp:
        src: /home/ansible/.ssh/id_rsa  # Ruta de la llave privada en la máquina local
      register: private_key_content

    - name: Mostrar el contenido de la llave privada (decodificado)
      debug:
        msg: "{{ private_key_content.content | b64decode }}"

    - name: Ejecutar comando remoto en 192.168.100.100 para obtener la distro
      ansible.builtin.shell: |
        uname -a
        cat /etc/*release
      delegate_to: 192.168.100.100  # El comando se ejecuta en la máquina remota
      remote_user: webserver  # El usuario remoto
      ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa  # Ruta de la llave privada
      register: remote_distro_info

    - name: Mostrar la información de la distribución y versión del sistema operativo
      debug:
        msg: "{{ remote_distro_info.stdout }}"
