---
- name: Ejecutar otro playbook en la máquina local
  hosts: local
  gather_facts: no

  tasks:
    - name: Ejecutar el playbook /home/ansible/ejemplo/ejemplo.yml
      import_playbook: /home/ansible/ejemplo/ejemplo.yml  # Ruta al playbook que quieres ejecutar
