---
- name: Analizar sistema operativo de la máquina remota
  hosts: 192.168.100.100
  gather_facts: yes
  become: yes  # Esto se usa si necesitas privilegios elevados para obtener la información
  remote_user: webserver  # El usuario en la máquina remota (ajusta según sea necesario)

  tasks:
    - name: Mostrar información sobre el sistema operativo
      debug:
        msg: "La máquina remota tiene el sistema operativo {{ ansible_facts['os_family'] }} {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}."

  vars:
    ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa  # Ruta de la llave privada en la máquina 192.168.100.51
