---
- name: envio mail
  hosts: local
  become: yes
  vars:
    alert_days: 400  # Asegúrate de que este valor coincida con el anterior
  tasks:
      - name: Copiar script Python al host
        copy:
          src: python/send_email.py  # Ruta local del script Python
          dest: /tmp/send_email.py       # Ruta de destino en el host
          mode: '0755'
      
      - name: Ejecutar el script Python para enviar correo por cada certificado próximo a expirar
        command: python3 /tmp/send_email.py "