---
version: 1
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"
dependencies:
  python: requirements.txt
  # Si utilizas colecciones de Ansible Galaxy, puedes incluir un archivo requirements.yml
  # galaxy: requirements.yml
additional_build_steps:
  prepend: []
  append: []
