---
- name: Generar informe de vulnerabilidades y generar PDF
  hosts: local
  become: yes
  tasks:

    - name: Copiar el archivo import_requests.py desde el proyecto AAP
      copy:
        src: python/import_requests.py
        dest: /tmp/import_requests.py
        mode: '0755'

    - name: Copiar el archivo info.py desde el proyecto AAP
      copy:
        src: python/info.py
        dest: /tmp/info.py
        mode: '0755'

    - name: Copiar el archivo ejemplo.adoc desde el proyecto AAP
      copy:
        src: ejemplo.adoc
        dest: /tmp/ejemplo.adoc
        mode: '0644'

    - name: Ejecutar el script import_requests.py para generar archivos ASCII Doctor de vulnerabilidades
      command: python3 /tmp/import_requests.py
      args:
        chdir: /tmp

    - name: Ejecutar el script info.py para obtener imágenes desde Grafana
      command: python3 /tmp/info.py
      args:
        chdir: /tmp

    - name: Ejecutar AsciiDoctor para generar el PDF a partir del archivo ejemplo.adoc
      command: /home/ansible/bin/asciidoctor-pdf /tmp/ejemplo.adoc
      environment:
        GEM_PATH: "/home/ansible/.local/share/gem/ruby:/usr/share/gems:/usr/local/share/gems"
        GEM_HOME: "/home/ansible/.local/share/gem/ruby"

    - name: Mover el PDF generado al directorio /home/ansible/resultado
      command: mv /tmp/ejemplo.pdf /home/ansible/resultado/ejemplo.pdf

    - name: Verificar si el archivo ejemplo.pdf existe
      stat:
        path: /home/ansible/resultado/ejemplo.pdf
      register: example_pdf

    - name: Mostrar mensaje si el archivo no existe
      debug:
        msg: "El archivo ejemplo.pdf no existe en la ruta especificada"
      when: not example_pdf.stat.exists

    - name: Limpiar el contenido de /tmp sin borrar el directorio
      shell: rm -rf /tmp/*
      ignore_errors: yes

    - name: Enviar el archivo generado vía correo con sendmail desde un mail dummy
      shell: |
        (
        echo "Subject: Reporte generado"
        echo "From: juanpablo@betel-tech.cl"
        echo "To: jpreinosom@gmail.com"
        echo "MIME-Version: 1.0"
        echo "Content-Type: multipart/mixed; boundary=\"FILEBOUNDARY\""
        echo ""
        echo "--FILEBOUNDARY"
        echo "Content-Type: text/plain; charset=UTF-8"
        echo ""
        echo "Se adjunta el informe generado."
        echo ""
        echo "--FILEBOUNDARY"
        echo "Content-Type: application/pdf; name=\"ejemplo.pdf\""
        echo "Content-Transfer-Encoding: base64"
        echo "Content-Disposition: attachment; filename=\"ejemplo.pdf\""
        # Codificando el archivo PDF y directamente insertando en el correo
        base64 /home/ansible/resultado/ejemplo.pdf
        echo "--FILEBOUNDARY--"
        ) | /usr/sbin/sendmail -t -f juanpablo@betel-tech.cl
