---
# playbooks/instalar_scap_security_guide.yml

- name: Leer y procesar el inventario CSV para agregar hosts dinámicamente
  hosts: localhost
  gather_facts: no
  vars:
    input_file: "{{ playbook_dir }}/inventario.csv"
    delimiter: ";"
  tasks:
    - name: Verificar que el archivo CSV existe
      stat:
        path: "{{ input_file }}"
      register: file_check

    - name: Fallar si el archivo CSV no existe
      fail:
        msg: "El archivo de inventario {{ input_file }} no existe."
      when: not file_check.stat.exists

    - name: Leer contenido del archivo CSV
      command: cat "{{ input_file }}"
      register: csv_content

    - name: Dividir contenido en líneas
      set_fact:
        csv_lines: "{{ csv_content.stdout.split('\n') }}"

    - name: Extraer encabezados
      set_fact:
        csv_headers: "{{ csv_lines[0].split(delimiter) | map('trim') | list }}"

    - name: Crear lista de hosts
      set_fact:
        csv_hosts: "{{ csv_hosts | default([]) + [ dict(csv_headers[0:3] | zip(line.split(delimiter)[0:3])) ] }}"
      with_items: "{{ csv_lines[1:] }}"
      when: line.strip() != ''
      loop_control:
        loop_var: line
      vars:
        line: "{{ item }}"

    - name: Agregar hosts dinámicamente al grupo 'dynamic_hosts'
      add_host:
        name: "{{ item.IP }}"
        groups: "dynamic_hosts"
        ansible_host: "{{ item.IP }}"
        ansible_user: "{{ item.Usuario }}"
        ansible_password: "{{ item.Contraseña }}"
        ansible_connection: ssh
        ansible_ssh_pass: "{{ item.Contraseña }}"
      with_items: "{{ csv_hosts }}"
      loop_control:
        label: "{{ item.IP }}"
      delegate_to: localhost

- name: Instalar SCAP Security Guide y dependencias en Ubuntu
  hosts: ubuntu_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Habilitar repositorios universe
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar ssg-base y openscap-scanner
      apt:
        name:
          - ssg-base
          - openscap-scanner
          - xsltproc  # Asegúrate de que xsltproc está instalado
        state: present

    - name: Verificar si el archivo XML de SCAP Security Guide está presente
      stat:
        path: "/usr/share/xml/scap/ssg/content/ssg-ubuntu-{{ ansible_distribution_version.split('.')[0] }}.04-ds.xml"
      register: xml_file_check

    - name: Copiar el archivo XML si no está presente
      copy:
        src: "/usr/share/xml/scap/ssg/content/ssg-ubuntu-20.04-ds.xml"  # Ajustar según la versión instalada
        dest: "/usr/share/xml/scap/ssg/content/ssg-ubuntu-{{ ansible_distribution_version.split('.')[0] }}.04-ds.xml"
        owner: root
        group: root
        mode: '0644'
      when: not xml_file_check.stat.exists

    - name: Verificar la copia de archivos XML
      stat:
        path: "/usr/share/xml/scap/ssg/content/ssg-ubuntu-{{ ansible_distribution_version.split('.')[0] }}.04-ds.xml"
      register: final_check

    - name: Fallar si el archivo XML no se copió correctamente
      fail:
        msg: "No se pudo copiar el archivo XML de SCAP Security Guide para Ubuntu en {{ inventory_hostname }}"
      when: not final_check.stat.exists

- name: Instalar SCAP Security Guide y dependencias en CentOS/RHEL
  hosts: rhel_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Instalar openscap-scanner y scap-security-guide
      dnf:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Verificar la instalación de oscap
      command: which oscap
      register: scap_installed
      ignore_errors: yes

    - name: Asegurarse de que oscap está instalado
      fail:
        msg: "oscap no se pudo instalar en {{ inventory_hostname }}"
      when: scap_installed.rc != 0
