---
# playbooks/instalar_scap_security_guide.yml

- name: Leer y procesar el inventario CSV para agregar hosts dinámicamente
  hosts: localhost
  gather_facts: no
  vars:
    input_file: "{{ playbook_dir }}/inventario.csv"  # Ajusta la ruta según tu estructura
    delimiter: ";"
  tasks:
    - name: Verificar que el archivo CSV existe
      stat:
        path: "{{ input_file }}"
      register: file_check

    - name: Fallar si el archivo CSV no existe
      fail:
        msg: "El archivo de inventario {{ input_file }} no existe."
      when: not file_check.stat.exists

    - name: Leer contenido del archivo CSV
      command: cat "{{ input_file }}"
      register: csv_content

    - name: Dividir contenido en líneas
      set_fact:
        csv_lines: "{{ csv_content.stdout.split('\n') }}"

    - name: Extraer encabezados
      set_fact:
        csv_headers: "{{ csv_lines[0].split(delimiter) | map('trim') | list }}"

    - name: Crear lista de hosts
      set_fact:
        csv_hosts: "{{ csv_hosts | default([]) + [ dict(csv_headers[0:3] | zip(line.split(delimiter)[0:3])) ] }}"
      with_items: "{{ csv_lines[1:] }}"
      when: line.strip() != ''
      loop_control:
        loop_var: line
      vars:
        line: "{{ item }}"

    - name: Agregar hosts dinámicamente al grupo 'dynamic_hosts'
      add_host:
        name: "{{ item.IP }}"
        groups: "dynamic_hosts"
        ansible_host: "{{ item.IP }}"
        ansible_user: "{{ item.Usuario }}"
        ansible_password: "{{ item.Contraseña }}"
        ansible_connection: ssh
        ansible_ssh_pass: "{{ item.Contraseña }}"
      with_items: "{{ csv_hosts }}"
      loop_control:
        label: "{{ item.IP }}"
      delegate_to: localhost

    - name: Mostrar hosts agregados
      debug:
        msg: "Host agregado: {{ item.IP }} al grupo dynamic_hosts"
      with_items: "{{ csv_hosts }}"
      loop_control:
        label: "{{ item.IP }}"

- name: Agrupar hosts por distribución
  hosts: dynamic_hosts
  gather_facts: yes
  tasks:
    - name: Agrupar en 'ubuntu_hosts' si Ubuntu
      group_by:
        key: "ubuntu_hosts"
      when: ansible_distribution == "Ubuntu"

    - name: Agrupar en 'rhel_hosts' si RHEL/CentOS
      group_by:
        key: "rhel_hosts"
      when: ansible_distribution in ["CentOS", "RedHat", "OracleLinux", "AlmaLinux", "RockyLinux"]

- name: Instalar paquetes necesarios en Ubuntu/Debian
  hosts: ubuntu_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Habilitar repositorios universe
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar ssg-base y openscap-scanner
      apt:
        name:
          - ssg-base
          - openscap-scanner
        state: present

    - name: Verificar la instalación de oscap
      command: which oscap
      register: scap_installed
      ignore_errors: yes

    - name: Asegurarse de que oscap está instalado
      fail:
        msg: "oscap no se pudo instalar en {{ inventory_hostname }}"
      when: scap_installed.rc != 0

    - name: Descargar SCAP Security Guide
      git:
        repo: https://github.com/ComplianceAsCode/content.git
        dest: /tmp/content
        version: main
      when: ansible_distribution == "Ubuntu"

    - name: Compilar el contenido SCAP (Ubuntu)
      command: ./build.sh
      args:
        chdir: /tmp/content
      when:
        - ansible_distribution == "Ubuntu"
        - not lookup('pipe', "ls /tmp/content/build/content/ssg-ubuntu-*.xml 2>/dev/null")
      register: compile_ssg
      ignore_errors: yes

    - name: Copiar archivos XML de SCAP Security Guide para Ubuntu
      copy:
        src: "/tmp/content/build/content/ssg-ubuntu-{{ ansible_distribution_version.split('.')[0] }}.04-ds.xml"  # Ajusta según la versión
        dest: /usr/share/xml/scap/ssg/content/
        owner: root
        group: root
        mode: '0644'
      when:
        - ansible_distribution == "Ubuntu"
        - compile_ssg is succeeded
        - stat(path="/tmp/content/build/content/ssg-ubuntu-{{ ansible_distribution_version.split('.')[0] }}.04-ds.xml").exists

    - name: Verificar la copia de archivos XML
      stat:
        path: "/usr/share/xml/scap/ssg/content/ssg-ubuntu-{{ ansible_distribution_version.split('.')[0] }}.04-ds.xml"
      register: xml_file_check

    - name: Fallar si el archivo XML no se copió correctamente
      fail:
        msg: "No se pudo copiar el archivo XML de SCAP Security Guide para Ubuntu en {{ inventory_hostname }}"
      when:
        - ansible_distribution == "Ubuntu"
        - not xml_file_check.stat.exists

- name: Instalar paquetes necesarios en CentOS/RHEL
  hosts: rhel_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Instalar openscap-scanner y scap-security-guide
      dnf:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Verificar la instalación de oscap
      command: which oscap
      register: scap_installed
      ignore_errors: yes

    - name: Asegurarse de que oscap está instalado
      fail:
        msg: "oscap no se pudo instalar en {{ inventory_hostname }}"
      when: scap_installed.rc != 0
