---
# playbooks/instalar_openscap.yml

- name: Instalar OpenSCAP y scap-security-guide
  hosts: dynamic_hosts_openscap
  become: yes
  vars_files:
    - ../vars/eol_map.yml
  tasks:
    - name: Definir paquetes necesarios para OpenSCAP
      set_fact:
        openscap_packages: "{{ distribuciones_paquetes[ansible_distribution] | default([]) }}"

    - name: Mostrar paquetes a instalar para OpenSCAP
      debug:
        msg: "Paquetes a instalar para {{ ansible_distribution }}: {{ openscap_packages }}"

    - name: Habilitar el repositorio EPEL en CentOS/RHEL
      yum:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat"

    - name: Habilitar el repositorio EPEL en Fedora
      dnf:
        name: epel-release
        state: present
      when: ansible_os_family == "Fedora"

    - name: Instalar paquetes necesarios para OpenSCAP (Ubuntu/Debian)
      apt:
        name: "{{ openscap_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian" and openscap_packages | length > 0

    - name: Instalar scap-security-guide (Ubuntu/Debian)
      apt:
        name: scap-security-guide
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Instalar paquetes necesarios para OpenSCAP (CentOS/RHEL)
      yum:
        name: "{{ openscap_packages }}"
        state: present
      when: ansible_os_family == "RedHat" and openscap_packages | length > 0

    - name: Instalar scap-security-guide (CentOS/RHEL)
      yum:
        name: scap-security-guide
        state: present
      when: ansible_os_family == "RedHat"

    - name: Instalar paquetes necesarios para OpenSCAP (Fedora)
      dnf:
        name: "{{ openscap_packages }}"
        state: present
      when: ansible_os_family == "Fedora" and openscap_packages | length > 0

    - name: Instalar scap-security-guide (Fedora)
      dnf:
        name: scap-security-guide
        state: present
      when: ansible_os_family == "Fedora"

    - name: Verificar archivos SCAP disponibles
      command: ls /usr/share/xml/scap/ssg/content/
      register: scp_files
      changed_when: false

    - name: Mostrar archivos SCAP disponibles
      debug:
        var: scp_files.stdout_lines

    - name: Verificar existencia del archivo SCAP específico
      stat:
        path: "/usr/share/xml/scap/ssg/content/ssg-{{ ansible_distribution | lower }}-ds.xml"
      register: scap_file_check

    - name: Fallar si el archivo SCAP no existe
      fail:
        msg: "El archivo SCAP '/usr/share/xml/scap/ssg/content/ssg-{{ ansible_distribution | lower }}-ds.xml' no existe en {{ inventory_hostname }}."
      when: not scap_file_check.stat.exists

    - name: Verificar la instalación de OpenSCAP
      command: which oscap
      register: oscap_check
      changed_when: false
      ignore_errors: true

    - name: Mostrar resultado de la verificación de oscap
      debug:
        msg: "OpenSCAP está instalado en {{ inventory_hostname }}"
      when: oscap_check.rc == 0

    - name: Mostrar mensaje si OpenSCAP no está instalado
      debug:
        msg: "OpenSCAP no está instalado en {{ inventory_hostname }}"
      when: oscap_check.rc != 0
