---
- name: Instalar colecciones necesarias para interactuar con AWS
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Instalar colecci칩n amazon.aws
      ansible.builtin.pip:
        name: "amazon.aws"
        state: present
      become: yes
      tags: install

    - name: Verificar que la colecci칩n amazon.aws est치 instalada
      command: ansible-galaxy collection list amazon.aws
      register: result
      changed_when: false

    - name: Mostrar la instalaci칩n de amazon.aws
      debug:
        msg: "{{ result.stdout }}"
