---
# playbooks/instalar_scap_security_guide.yml

- name: Leer y procesar el inventario CSV para agregar hosts dinámicamente
  hosts: localhost
  gather_facts: no
  vars:
    input_file: "{{ playbook_dir }}/inventario.csv"  # Asegúrate de que esta ruta sea correcta
    delimiter: ";"
  tasks:
    - name: Verificar que el archivo CSV existe
      stat:
        path: "{{ input_file }}"
      register: file_check

    - name: Fallar si el archivo CSV no existe
      fail:
        msg: "El archivo de inventario {{ input_file }} no existe."
      when: not file_check.stat.exists

    - name: Leer contenido del archivo CSV
      command: cat "{{ input_file }}"
      register: csv_content

    - name: Dividir contenido en líneas
      set_fact:
        csv_lines: "{{ csv_content.stdout.split('\n') }}"

    - name: Extraer encabezados
      set_fact:
        csv_headers: "{{ csv_lines[0].split(delimiter) | map('trim') | list }}"

    - name: Crear lista de hosts
      set_fact:
        csv_hosts: "{{ csv_hosts | default([]) + [ dict(csv_headers[0:3] | zip(line.split(delimiter)[0:3])) ] }}"
      with_items: "{{ csv_lines[1:] }}"
      when: line.strip() != ''
      loop_control:
        loop_var: line
      vars:
        line: "{{ item }}"

    - name: Agregar hosts dinámicamente al grupo 'dynamic_hosts'
      add_host:
        name: "{{ item.IP }}"
        groups: "dynamic_hosts"
        ansible_host: "{{ item.IP }}"
        ansible_user: "{{ item.Usuario }}"
        ansible_password: "{{ item.Contraseña }}"
        ansible_connection: ssh
        ansible_ssh_pass: "{{ item.Contraseña }}"
      with_items: "{{ csv_hosts }}"
      loop_control:
        label: "{{ item.IP }}"
      delegate_to: localhost

- name: Agrupar hosts por distribución
  hosts: dynamic_hosts
  gather_facts: yes
  tasks:
    - name: Agrupar en 'ubuntu_hosts' si Ubuntu
      group_by:
        key: "ubuntu_hosts"
      when: ansible_distribution == "Ubuntu"

    - name: Agrupar en 'rhel_hosts' si RHEL/CentOS
      group_by:
        key: "rhel_hosts"
      when: ansible_distribution in ["CentOS", "RedHat", "OracleLinux", "AlmaLinux", "RockyLinux"]

- name: Instalar SCAP Security Guide en Ubuntu
  hosts: ubuntu_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Habilitar repositorios universe
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar ssg-base, openscap-scanner y git
      apt:
        name:
          - ssg-base
          - ssg-debderived
          - ssg-debian
          - ssg-nondebian
          - ssg-applications
          - openscap-scanner
        state: present

    - name: Verificar la instalación de oscap
      command: which oscap
      register: scap_installed
      ignore_errors: yes

    - name: Asegurarse de que oscap está instalado
      fail:
        msg: "oscap no se pudo instalar en {{ inventory_hostname }}"
      when: scap_installed.rc != 0

    - name: Verificar existencia de archivos XML de SCAP
      stat:
        path: "/usr/share/xml/scap/ssg/content/ssg-ubuntu-{{ ansible_distribution_version.split('.')[0] }}.04-ds.xml"
      register: xml_file_check

    - name: Fallar si el archivo XML no existe
      fail:
        msg: "El archivo XML de SCAP Security Guide no se encontró en {{ inventory_hostname }}"
      when: not xml_file_check.stat.exists

- name: Instalar SCAP Security Guide en CentOS/RHEL
  hosts: rhel_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Instalar openscap-scanner y scap-security-guide
      dnf:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Verificar la instalación de oscap
      command: which oscap
      register: scap_installed
      ignore_errors: yes

    - name: Asegurarse de que oscap está instalado
      fail:
        msg: "oscap no se pudo instalar en {{ inventory_hostname }}"
      when: scap_installed.rc != 0

    - name: Verificar existencia de archivos XML de SCAP
      stat:
        path: "/usr/share/xml/scap/ssg/content/ssg-redhat-ds.xml"
      register: xml_file_check_rhel

    - name: Fallar si el archivo XML no existe
      fail:
        msg: "El archivo XML de SCAP Security Guide no se encontró en {{ inventory_hostname }}"
      when: not xml_file_check_rhel.stat.exists
