---
- name: Leer y mostrar informaci칩n del inventario CSV
  hosts: localhost
  gather_facts: no
  vars:
    input_file: "/tmp/inventario.csv"
  tasks:
    - name: Leer datos desde el archivo CSV usando lookup csvfile
      set_fact:
        csv_data: "{{ lookup('csvfile', input_file, delimiter=';') }}"

    - name: Mostrar estructura completa de csv_data
      debug:
        var: csv_data

    - name: Mostrar informaci칩n de cada entrada del inventario
      debug:
        msg: "IP: {{ item.IP }}, Usuario: {{ item.Usuario }}, Contrase침a: {{ item.Contrase침a }}"
      loop: "{{ csv_data }}"
