---
# playbooks/analizar_vulnerabilidades_windows.yml

- name: Leer y procesar el inventario CSV (Windows)
  hosts: localhost
  gather_facts: no
  vars:
    input_file_windows: "{{ playbook_dir }}/inventory/inventarioWindows.csv"
    grafana_file: "{{ playbook_dir }}/inventory/grafana.csv"
    delimiter: ";"
  tasks:
    - name: Verificar que el archivo CSV de Windows existe
      stat:
        path: "{{ input_file_windows }}"
      register: file_check_windows

    - name: Fallar si el archivo de inventario Windows no existe
      fail:
        msg: "El archivo de inventario Windows {{ input_file_windows }} no existe."
      when: not file_check_windows.stat.exists

    - name: Leer contenido del archivo CSV de Windows
      set_fact:
        csv_content_windows: "{{ lookup('file', input_file_windows) }}"

    - name: Extraer encabezados del CSV de Windows
      set_fact:
        headers_windows: "{{ csv_content_windows.split('\n') | first | split(delimiter) | map('trim') | list }}"

    - name: Extraer filas del CSV de Windows
      set_fact:
        rows_windows: "{{ csv_content_windows.split('\n')[1:] | reject('match', '^$') | list | map('split', delimiter) | list }}"

    - name: Validar que cada fila del archivo de inventario Windows tenga el mismo número de campos que los encabezados
      fail:
        msg: "La fila {{ row }} no tiene el mismo número de campos que los encabezados."
      when: row | length != headers_windows | length
      loop: "{{ rows_windows }}"
      loop_control:
        loop_var: row

    - name: Combinar encabezados con filas del CSV de Windows para crear diccionarios
      set_fact:
        csv_data_windows: "{{ csv_data_windows | default([]) + [ dict(headers_windows | zip(row)) ] }}"
      loop: "{{ rows_windows }}"
      loop_control:
        loop_var: row

    - name: Agregar hosts dinámicamente al grupo 'dynamic_hosts' para Windows
      add_host:
        name: "{{ item.IP }}"
        groups: dynamic_hosts
        ansible_host: "{{ item.IP }}"
        ansible_user: "{{ item.Usuario }}"
        ansible_password: "{{ item.Contraseña }}"
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        remote_tmp: C:\\tmp\\ansible
      loop: "{{ csv_data_windows }}"
      loop_control:
        loop_var: item

- name: Obtener información y verificar EoL de los servidores Windows
  hosts: dynamic_hosts
  gather_facts: yes
  tasks:
    - name: Determinar la familia del sistema operativo para Windows
      set_fact:
        os_family: Windows

    - name: Obtener la fecha actual del sistema
      set_fact:
        current_date: "{{ ansible_date_time.date | regex_replace('-', '') }}"  # YYYYMMDD

    - name: Obtener facts del sistema para Windows
      setup:
        gather_subset:
          - system  # Solo recopila información sobre el sistema (como distribución, versión, etc.)

    - name: Determinar la fecha de EoL para la versión de Windows
      set_fact:
        eol_date: >-
          {{
            (eol_map.get(ansible_distribution, {})
            | dict2items
            | selectattr('key', '==', ansible_distribution_version)
            | map(attribute='value')
            | list
            | first)
            | default(
              (eol_map.get(ansible_distribution, {})
              | dict2items
              | selectattr('key', '==', ansible_distribution_version.split('.')[0])
              | map(attribute='value')
              | list
              | first),
              None
            )
          }}

    - name: Establecer el estado de suscripción para Windows
      set_fact:
        subscription_status: >-
          {% if eol_date is defined %}
            {% if eol_date == "rolling" %}
              Rolling Release
            {% elif current_date | int > (eol_date | regex_replace('-', '') | int) %}
              Deprecado
            {% else %}
              Soportada
            {% endif %}
          {% else %}
            Versión sin fecha establecida de EoL
          {% endif %}

    - name: Mostrar información del sistema operativo para Windows
      debug:
        msg: "Distribución: {{ ansible_distribution }}, Versión: {{ ansible_distribution_version }}, Familia: {{ os_family }}"

- name: Insertar registros en la tabla inventario en la base de datos
  hosts: grafana_hosts
  become: yes
  tasks:
    - name: Insertar registros desde csv_data_windows en la base de datos
      command: >
        psql -U grafana_user -d grafana_db -c "
        INSERT INTO inventario (
          ip, distribucion, version, familia, soportada, usuario, password
        ) VALUES (
          '{{ item.IP }}',
          '{{ hostvars[item.IP]['ansible_distribution'] | default('No disponible') }}',
          '{{ hostvars[item.IP]['ansible_distribution_version'] | default('No disponible') }}',
          '{{ hostvars[item.IP]['os_family'] | default('No disponible') }}',
          '{{ hostvars[item.IP]['subscription_status'] | default('No definido') | trim }}',
          '{{ item.Usuario }}',  # Aquí se agrega el campo Usuario
          '{{ item.Contraseña }}'  # Aquí se agrega el campo Contraseña
        )
        "
      loop: "{{ hostvars['localhost']['csv_data_windows'] }}"
      loop_control:
        loop_var: item
      environment:
        PGPASSWORD: "grafana_password"
      become: no
