---
- name: Procesar hosts desde archivo CSV
  hosts: localhost
  gather_facts: no
  vars:
    input_file: "/tmp/inventario.csv"
    output_file: "/tmp/resultado.csv"
  tasks:
    - name: Leer datos desde el archivo CSV
      read_csv:
        path: "{{ input_file }}"
        delimiter: ';'
      register: csv_data

    - name: Inicializar lista de resultados
      set_fact:
        result_list: []

    - name: Procesar cada entrada del CSV
      vars:
        host_entry: "{{ item }}"
      loop: "{{ csv_data.list }}"
      tasks:
        - name: Agregar host dinámicamente
          add_host:
            name: "{{ host_entry['IP'] }}"
            ansible_user: "{{ host_entry['Usuario'] }}"
            ansible_password: "{{ host_entry['Contraseña'] }}"
            ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
            groups: dynamic_hosts

- name: Recopilar información de los hosts
  hosts: dynamic_hosts
  gather_facts: yes
  tasks:
    - name: Obtener información del sistema
      set_fact:
        os_info:
          IP: "{{ ansible_host }}"
          Distribucion: "{{ ansible_distribution }}"
          Version: "{{ ansible_distribution_version }}"
          Usuario: "{{ ansible_user }}"
          Contraseña: "{{ ansible_password }}"

    - name: Agregar información a la lista de resultados
      run_once: true
      set_fact:
        result_list: "{{ result_list + [os_info] }}"
      delegate_to: localhost

- name: Escribir resultados en archivo CSV
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Formatear datos para CSV
      set_fact:
        csv_output: |
          IP;Distribucion;Version;Usuario;Contraseña
          {% for item in result_list %}
          {{ item.IP }};{{ item.Distribucion }};{{ item.Version }};{{ item.Usuario }};{{ item.Contraseña }}
          {% endfor %}

    - name: Escribir datos en CSV
      copy:
        content: "{{ csv_output }}"
        dest: "{{ output_file }}"
